# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build and deploy page

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout pages branch
      uses: actions/checkout@v4
    - name: use node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'v14.x'
    - name: install deps
      run: npm ci
    - name: build
      run: |
        mkdir -p build/node_modules/two.js/build
        cp *.js build/
        cp node_modules/two.js/build/two.js build/node_modules/two.js/build/
        cp index.html build/
    - name: upload build
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy build
        id: deployment
        uses: actions/deploy-pages@v4
